import { expect, test } from "@playwright/test";

test("Paper components support both languages, stock limits, validation and recovery", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/components-preview");
  await expect(page.getByText("معاينة المكونات", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "English", exact: true }).click();
  await expect(page.getByText("Component preview", { exact: true })).toBeVisible();
  await expect(page.locator("html")).toHaveAttribute("dir", "ltr");
  await page.getByLabel("Email", { exact: true }).fill("bad");
  await expect(page.getByText("Enter a valid email", { exact: true })).toBeVisible();
  await page.getByLabel("Email", { exact: true }).fill("sample@example.com");
  await expect(page.getByText("Enter a valid email", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Increase quantity", exact: true }).first().click();
  await page.getByRole("button", { name: "Increase quantity", exact: true }).first().click();
  await expect(page.getByRole("button", { name: "Increase quantity", exact: true }).first()).toBeDisabled();
  await page.getByRole("radio", { name: "Price: low to high", exact: true }).click();
  await expect(page.getByRole("radio", { name: "Price: low to high", exact: true })).toBeChecked();
  await page.getByRole("button", { name: "Not now", exact: true }).click();
  await expect(page.getByText("Sample optional update", { exact: true })).toHaveCount(0);
  await expect(page.getByText("Update needed for this feature", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Try again", exact: true }).click();
  await expect(page.getByText("Sample: couldn't load data", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Open confirmation", exact: true }).click();
  await expect(page.getByText("Sample confirmation", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByText("Sample confirmation", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "View full screen", exact: true }).click();
  await page.getByRole("button", { name: "Close", exact: true }).click();
  await page.getByRole("button", { name: "العربية", exact: true }).click();
  await expect(page.getByText("معاينة المكونات", { exact: true })).toBeVisible();
  await expect(page.locator("html")).toHaveAttribute("dir", "rtl");
  await expect(page.getByRole("button", { name: "العربية", exact: true })).toBeEnabled();
  await page.screenshot({ path: testInfo.outputPath("phase5-ar.png"), fullPage: true });
  await page.getByText("الوسائط", { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("phase5-ar-media.png") });
  await page.getByRole("button", { name: "English", exact: true }).click();
  await page.setViewportSize({ width: 320, height: 844 });
  await expect(page.getByRole("button", { name: "English", exact: true })).toBeEnabled();
  await page.screenshot({ path: testInfo.outputPath("phase5-en-320.png"), fullPage: true });
  await page.getByText("Recovery and updates", { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("phase5-en-recovery.png") });
  expect(errors).toEqual([]);
});
